// <auto-generated />
namespace CustomerInquiry.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class insert_customers_transactions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(insert_customers_transactions));
        
        string IMigrationMetadata.Id
        {
            get { return "201904172115228_insert_customers_transactions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
